-- création des tablespaces, users CYTECH_CERGY/CYTECH_PAU et grants
-- de base. à faire UNE fois (ou après une purge).
--
-- doit être lancé en SYS AS SYSDBA dans la PDB.
--
-- usage :
--   docker exec -it oracle-xe sqlplus sys/oracle@FREEPDB1 as sysdba
--   SQL> @/workspace/scripts/00_to_start.sql
-- ============================================================


ALTER SESSION SET CONTAINER = FREEPDB1;


-- ---- tablespaces Cergy ----
CREATE TABLESPACE DATA_CERGY
  DATAFILE 'data_cergy.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE IDX_CERGY
  DATAFILE 'idx_cergy.dbf' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE 200M
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


-- ---- tablespaces Pau ----
CREATE TABLESPACE DATA_PAU
  DATAFILE 'data_pau.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE IDX_PAU
  DATAFILE 'idx_pau.dbf' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE 200M
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


-- ---- user Cergy + grants ----
CREATE USER CYTECH_CERGY IDENTIFIED BY cergy2026
  DEFAULT TABLESPACE DATA_CERGY
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATA_CERGY
  QUOTA UNLIMITED ON IDX_CERGY;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SYNONYM,
      CREATE DATABASE LINK, CREATE SEQUENCE, CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE CLUSTER
   TO CYTECH_CERGY;


-- ---- user Pau + grants ----
CREATE USER CYTECH_PAU IDENTIFIED BY pau2026
  DEFAULT TABLESPACE DATA_PAU
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATA_PAU
  QUOTA UNLIMITED ON IDX_PAU;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SYNONYM,
      CREATE DATABASE LINK, CREATE SEQUENCE, CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE CLUSTER
   TO CYTECH_PAU;


-- ---- vérif ----
PROMPT
PROMPT === users créés ===
SELECT username, default_tablespace FROM dba_users
 WHERE username IN ('CYTECH_CERGY','CYTECH_PAU');

PROMPT === tablespaces créés ===
SELECT tablespace_name, status FROM dba_tablespaces
 WHERE tablespace_name IN ('DATA_CERGY','IDX_CERGY','DATA_PAU','IDX_PAU');
