-- ============================================================
--  SCRIPT 3 : RÔLES ORACLE ET UTILISATEUR ADMIN GLOBAL
--  À exécuter en tant que SYSDBA (après les scripts 1 et 2)
-- ============================================================


-- ============================================================
-- 1. RÔLES ORACLE (niveau SGBD)
-- ============================================================

CREATE ROLE ROLE_ADMIN_GLOBAL;
CREATE ROLE ROLE_IT_CERGY;
CREATE ROLE ROLE_IT_PAU;
CREATE ROLE ROLE_USER_CERGY;
CREATE ROLE ROLE_USER_PAU;
CREATE ROLE ROLE_AUDITEUR;


-- ============================================================
-- 2. PRIVILÈGES PAR RÔLE
-- ============================================================

-- ADMIN GLOBAL : lecture + écriture sur tout + vues globales
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.ASSET                     TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.APP_USER                  TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.NETWORK_PORT               TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.IP_ADDRESS                 TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.ASSET_ASSIGNMENT_HISTORY   TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.ASSET_MOVEMENT             TO ROLE_ADMIN_GLOBAL;
GRANT SELECT                          ON CYTECH_CERGY.V_GLOBAL_ASSET            TO ROLE_ADMIN_GLOBAL;
GRANT SELECT                          ON CYTECH_CERGY.V_GLOBAL_NETWORK          TO ROLE_ADMIN_GLOBAL;
GRANT SELECT                          ON CYTECH_CERGY.V_GLOBAL_ASSIGNMENT       TO ROLE_ADMIN_GLOBAL;

GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.ASSET                        TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.APP_USER                     TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.NETWORK_PORT                 TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.IP_ADDRESS                   TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.ASSET_ASSIGNMENT_HISTORY     TO ROLE_ADMIN_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.ASSET_MOVEMENT               TO ROLE_ADMIN_GLOBAL;

-- IT CERGY : lecture + écriture sur son schéma local seulement
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.ASSET                     TO ROLE_IT_CERGY;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.APP_USER                  TO ROLE_IT_CERGY;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.NETWORK_PORT               TO ROLE_IT_CERGY;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.IP_ADDRESS                 TO ROLE_IT_CERGY;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.ASSET_ASSIGNMENT_HISTORY   TO ROLE_IT_CERGY;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_CERGY.ASSET_MOVEMENT             TO ROLE_IT_CERGY;
GRANT SELECT                          ON CYTECH_CERGY.VLAN                      TO ROLE_IT_CERGY;
GRANT SELECT                          ON CYTECH_CERGY.NETWORK_SEGMENT           TO ROLE_IT_CERGY;

-- IT PAU : idem côté Pau
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.ASSET                        TO ROLE_IT_PAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.APP_USER                     TO ROLE_IT_PAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.NETWORK_PORT                 TO ROLE_IT_PAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.IP_ADDRESS                   TO ROLE_IT_PAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.ASSET_ASSIGNMENT_HISTORY     TO ROLE_IT_PAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYTECH_PAU.ASSET_MOVEMENT               TO ROLE_IT_PAU;
GRANT SELECT                          ON CYTECH_PAU.VLAN                        TO ROLE_IT_PAU;
GRANT SELECT                          ON CYTECH_PAU.NETWORK_SEGMENT             TO ROLE_IT_PAU;

-- USER CERGY : lecture restreinte (vue sur son schéma uniquement)
GRANT SELECT ON CYTECH_CERGY.ASSET   TO ROLE_USER_CERGY;
GRANT SELECT ON CYTECH_CERGY.APP_USER TO ROLE_USER_CERGY;

-- USER PAU
GRANT SELECT ON CYTECH_PAU.ASSET     TO ROLE_USER_PAU;
GRANT SELECT ON CYTECH_PAU.APP_USER   TO ROLE_USER_PAU;

-- AUDITEUR : lecture globale (vues fédérées uniquement)
GRANT SELECT ON CYTECH_CERGY.V_GLOBAL_ASSET       TO ROLE_AUDITEUR;
GRANT SELECT ON CYTECH_CERGY.V_GLOBAL_NETWORK      TO ROLE_AUDITEUR;
GRANT SELECT ON CYTECH_CERGY.V_GLOBAL_ASSIGNMENT   TO ROLE_AUDITEUR;


-- ============================================================
-- 3. UTILISATEURS ORACLE
-- ============================================================

-- Admin global de l'école (accès aux 2 bases)
CREATE USER ADMIN_CYTECH IDENTIFIED BY adminCY2026
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO ADMIN_CYTECH;
GRANT ROLE_ADMIN_GLOBAL TO ADMIN_CYTECH;

-- Technicien Cergy
CREATE USER TECH_CERGY IDENTIFIED BY techCGY2026
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO TECH_CERGY;
GRANT ROLE_IT_CERGY TO TECH_CERGY;

-- Technicien Pau
CREATE USER TECH_PAU IDENTIFIED BY techPAU2026
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO TECH_PAU;
GRANT ROLE_IT_PAU TO TECH_PAU;

-- Auditeur / BI
CREATE USER AUDIT_USER IDENTIFIED BY audit2026
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO AUDIT_USER;
GRANT ROLE_AUDITEUR TO AUDIT_USER;


-- ============================================================
-- 4. SYNONYMES PUBLICS (transparence de localisation)
--    L'admin voit "ASSET" sans préciser le schéma
-- ============================================================

CREATE PUBLIC SYNONYM GLOBAL_ASSET       FOR CYTECH_CERGY.V_GLOBAL_ASSET;
CREATE PUBLIC SYNONYM GLOBAL_NETWORK     FOR CYTECH_CERGY.V_GLOBAL_NETWORK;
CREATE PUBLIC SYNONYM GLOBAL_ASSIGNMENT  FOR CYTECH_CERGY.V_GLOBAL_ASSIGNMENT;


-- ============================================================
-- FIN DU SCRIPT RÔLES
-- ============================================================
