-- ============================================================
-- 03_setup_admin.sql
-- Connexion : / AS SYSDBA dans FREEPDB1
-- ============================================================
CONNECT / AS SYSDBA
ALTER SESSION SET CONTAINER = FREEPDB1;

-- ============================================================
-- 1. ROLES
-- ============================================================

-- Rôle lecture seule sur les 2 sites
CREATE ROLE CYTECH_READER;

GRANT SELECT ON CYTECH_CERGY.SITE               TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.PERSON             TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.DEVICE             TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.PERIPHERAL         TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.BUILDING           TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.ROOM               TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.MAINTENANCE_TICKET TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.DEVICE_TYPE        TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.OS_FAMILY          TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.OS_VERSION         TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.PERSON_ROLE        TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.PERIPHERAL_TYPE    TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.DEVICE_ASSIGNMENT  TO CYTECH_READER;

GRANT SELECT ON CYTECH_PAU.SITE                 TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.PERSON               TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.DEVICE               TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.PERIPHERAL           TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.BUILDING             TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.ROOM                 TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.DEVICE_TYPE          TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.OS_FAMILY            TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.OS_VERSION           TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.PERSON_ROLE          TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.PERIPHERAL_TYPE      TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.DEVICE_ASSIGNMENT    TO CYTECH_READER;

-- Rôle admin hérite du reader + droits écriture
CREATE ROLE CYTECH_ADMIN_ROLE;

GRANT CYTECH_READER TO CYTECH_ADMIN_ROLE;

GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.PERSON             TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.DEVICE             TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.PERIPHERAL         TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.BUILDING           TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.ROOM               TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.MAINTENANCE_TICKET TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.DEVICE_ASSIGNMENT  TO CYTECH_ADMIN_ROLE;

GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.PERSON               TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.DEVICE               TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.PERIPHERAL           TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.BUILDING             TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.ROOM                 TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.DEVICE_ASSIGNMENT    TO CYTECH_ADMIN_ROLE;

-- Tables de référence : INSERT/UPDATE seulement (pas de DELETE)
GRANT INSERT, UPDATE ON CYTECH_CERGY.SITE             TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_CERGY.DEVICE_TYPE      TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_CERGY.OS_FAMILY        TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_CERGY.OS_VERSION       TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_CERGY.PERSON_ROLE      TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_CERGY.PERIPHERAL_TYPE  TO CYTECH_ADMIN_ROLE;

-- ============================================================
-- 2. USER ADMIN
-- ============================================================
CREATE USER CYTECH_ADMIN IDENTIFIED BY admin2026
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION    TO CYTECH_ADMIN;
GRANT CYTECH_ADMIN_ROLE TO CYTECH_ADMIN;

-- Privileges necessaires pour les packages et triggers de replication
GRANT CREATE PROCEDURE TO CYTECH_CERGY;
GRANT CREATE PROCEDURE TO CYTECH_PAU;
GRANT CREATE TRIGGER   TO CYTECH_CERGY;
GRANT CREATE TRIGGER   TO CYTECH_PAU;

-- ============================================================
-- 3. VERIFICATION
-- ============================================================
SELECT grantee, granted_role
FROM dba_role_privs
WHERE grantee IN ('CYTECH_ADMIN', 'CYTECH_ADMIN_ROLE')
ORDER BY grantee;