-- ============================================================
-- role_gestion.sql
-- A executer apres :
--   01_setup_cergy.sql
--   02_setup_pau-2.sql
--   03_replication-3.sql
--
-- Objectif :
--   1. Creer les roles applicatifs
--   2. Attribuer les privileges sur les objets
--   3. Conserver CYTECH_CERGY et CYTECH_PAU comme schemas principaux
--   4. Creer 3 utilisateurs de test pour Cergy
--   5. Creer 3 utilisateurs de test pour Pau
-- ============================================================

CONNECT / AS SYSDBA;
ALTER SESSION SET CONTAINER = FREEPDB1;

-- ============================================================
-- 0. NETTOYAGE OPTIONNEL
-- Decommenter seulement si tu veux rejouer le script
-- ============================================================
-- DROP USER U_CERGY_READ CASCADE;
-- DROP USER U_CERGY_MANAGER CASCADE;
-- DROP USER U_CERGY_ADMIN CASCADE;
-- DROP USER U_PAU_READ CASCADE;
-- DROP USER U_PAU_MANAGER CASCADE;
-- DROP USER U_PAU_ADMIN CASCADE;

-- DROP ROLE R_CERGY_ADMIN;
-- DROP ROLE R_CERGY_MANAGER;
-- DROP ROLE R_CERGY_READ;
-- DROP ROLE R_PAU_ADMIN;
-- DROP ROLE R_PAU_MANAGER;
-- DROP ROLE R_PAU_READ;

-- ============================================================
-- 1. CREATION DES ROLES
-- ============================================================
CREATE ROLE R_CERGY_READ;
CREATE ROLE R_CERGY_MANAGER;
CREATE ROLE R_CERGY_ADMIN;

CREATE ROLE R_PAU_READ;
CREATE ROLE R_PAU_MANAGER;
CREATE ROLE R_PAU_ADMIN;

-- ============================================================
-- 2. HIERARCHIE DES ROLES
-- ============================================================
GRANT R_CERGY_READ TO R_CERGY_MANAGER;
GRANT R_CERGY_MANAGER TO R_CERGY_ADMIN;

GRANT R_PAU_READ TO R_PAU_MANAGER;
GRANT R_PAU_MANAGER TO R_PAU_ADMIN;

-- ============================================================
-- 3. PRIVILEGES SUR LES OBJETS DE CERGY
-- ============================================================
CONNECT CYTECH_CERGY/cergy2026@//localhost:1521/FREEPDB1;

-- ----------------------------
-- CERGY : lecture
-- ----------------------------
GRANT SELECT ON DEVICE_TYPE TO R_CERGY_READ;
GRANT SELECT ON OS_FAMILY TO R_CERGY_READ;
GRANT SELECT ON OS_VERSION TO R_CERGY_READ;
GRANT SELECT ON PERIPHERAL_TYPE TO R_CERGY_READ;
GRANT SELECT ON BUILDING TO R_CERGY_READ;
GRANT SELECT ON ROOM TO R_CERGY_READ;
GRANT SELECT ON PERSON TO R_CERGY_READ;
GRANT SELECT ON VLAN TO R_CERGY_READ;
GRANT SELECT ON NETWORK_SWITCH TO R_CERGY_READ;
GRANT SELECT ON DEVICE TO R_CERGY_READ;
GRANT SELECT ON PERIPHERAL TO R_CERGY_READ;
GRANT SELECT ON DEVICE_ASSIGNMENT TO R_CERGY_READ;
GRANT SELECT ON MAINTENANCE_TICKET TO R_CERGY_READ;
GRANT SELECT ON V_NETWORK_TOPOLOGY TO R_CERGY_READ;
GRANT SELECT ON V_ACTIVE_TICKETS TO R_CERGY_READ;
GRANT SELECT ON MV_SITE TO R_CERGY_READ;
GRANT SELECT ON MV_PERSON_ROLE TO R_CERGY_READ;
GRANT SELECT ON V_PAU_DEVICE_MIN TO R_CERGY_READ;

-- ----------------------------
-- CERGY : gestion locale
-- ----------------------------
GRANT INSERT, UPDATE ON BUILDING TO R_CERGY_MANAGER;
GRANT INSERT, UPDATE ON ROOM TO R_CERGY_MANAGER;
GRANT INSERT, UPDATE ON PERSON TO R_CERGY_MANAGER;
GRANT INSERT, UPDATE ON VLAN TO R_CERGY_MANAGER;
GRANT INSERT, UPDATE ON NETWORK_SWITCH TO R_CERGY_MANAGER;
GRANT INSERT, UPDATE ON DEVICE TO R_CERGY_MANAGER;
GRANT INSERT, UPDATE ON PERIPHERAL TO R_CERGY_MANAGER;
GRANT INSERT, UPDATE ON DEVICE_ASSIGNMENT TO R_CERGY_MANAGER;
GRANT INSERT, UPDATE ON MAINTENANCE_TICKET TO R_CERGY_MANAGER;

GRANT SELECT ON SEQ_PERSON_CERGY TO R_CERGY_MANAGER;
GRANT SELECT ON SEQ_DEVICE_CERGY TO R_CERGY_MANAGER;
GRANT SELECT ON SEQ_PERIPH_CERGY TO R_CERGY_MANAGER;
GRANT SELECT ON SEQ_TICKET_ID TO R_CERGY_MANAGER;

GRANT EXECUTE ON PROC_CREATE_TICKET TO R_CERGY_MANAGER;

-- ----------------------------
-- CERGY : administration
-- ----------------------------
GRANT INSERT, UPDATE, DELETE ON DEVICE_TYPE TO R_CERGY_ADMIN;
GRANT INSERT, UPDATE, DELETE ON OS_FAMILY TO R_CERGY_ADMIN;
GRANT INSERT, UPDATE, DELETE ON OS_VERSION TO R_CERGY_ADMIN;
GRANT INSERT, UPDATE, DELETE ON PERIPHERAL_TYPE TO R_CERGY_ADMIN;

GRANT DELETE ON BUILDING TO R_CERGY_ADMIN;
GRANT DELETE ON ROOM TO R_CERGY_ADMIN;
GRANT DELETE ON PERSON TO R_CERGY_ADMIN;
GRANT DELETE ON VLAN TO R_CERGY_ADMIN;
GRANT DELETE ON NETWORK_SWITCH TO R_CERGY_ADMIN;
GRANT DELETE ON DEVICE TO R_CERGY_ADMIN;
GRANT DELETE ON PERIPHERAL TO R_CERGY_ADMIN;
GRANT DELETE ON DEVICE_ASSIGNMENT TO R_CERGY_ADMIN;
GRANT DELETE ON MAINTENANCE_TICKET TO R_CERGY_ADMIN;

-- ============================================================
-- 4. PRIVILEGES SUR LES OBJETS DE PAU
-- ============================================================
CONNECT CYTECH_PAU/pau2026@//localhost:1521/FREEPDB1;

-- ----------------------------
-- PAU : lecture
-- ----------------------------
GRANT SELECT ON SITE TO R_PAU_READ;
GRANT SELECT ON PERSON_ROLE TO R_PAU_READ;
GRANT SELECT ON BUILDING TO R_PAU_READ;
GRANT SELECT ON ROOM TO R_PAU_READ;
GRANT SELECT ON PERSON TO R_PAU_READ;
GRANT SELECT ON VLAN TO R_PAU_READ;
GRANT SELECT ON NETWORK_SWITCH TO R_PAU_READ;
GRANT SELECT ON DEVICE TO R_PAU_READ;
GRANT SELECT ON PERIPHERAL TO R_PAU_READ;
GRANT SELECT ON DEVICE_ASSIGNMENT TO R_PAU_READ;
GRANT SELECT ON V_NETWORK_TOPOLOGY TO R_PAU_READ;
GRANT SELECT ON MV_DEVICE_TYPE TO R_PAU_READ;
GRANT SELECT ON MV_PERIPHERAL_TYPE TO R_PAU_READ;
GRANT SELECT ON MV_OS_FAMILY TO R_PAU_READ;
GRANT SELECT ON MV_OS_VERSION TO R_PAU_READ;
GRANT SELECT ON V_CERGY_TICKET_MIN TO R_PAU_READ;

-- ----------------------------
-- PAU : gestion locale
-- ----------------------------
GRANT INSERT, UPDATE ON BUILDING TO R_PAU_MANAGER;
GRANT INSERT, UPDATE ON ROOM TO R_PAU_MANAGER;
GRANT INSERT, UPDATE ON PERSON TO R_PAU_MANAGER;
GRANT INSERT, UPDATE ON VLAN TO R_PAU_MANAGER;
GRANT INSERT, UPDATE ON NETWORK_SWITCH TO R_PAU_MANAGER;
GRANT INSERT, UPDATE ON DEVICE TO R_PAU_MANAGER;
GRANT INSERT, UPDATE ON PERIPHERAL TO R_PAU_MANAGER;
GRANT INSERT, UPDATE ON DEVICE_ASSIGNMENT TO R_PAU_MANAGER;

GRANT SELECT ON SEQ_PERSON_PAU TO R_PAU_MANAGER;
GRANT SELECT ON SEQ_DEVICE_PAU TO R_PAU_MANAGER;
GRANT SELECT ON SEQ_PERIPH_PAU TO R_PAU_MANAGER;

GRANT EXECUTE ON PROC_OPEN_TICKET_PAU TO R_PAU_MANAGER;

-- ----------------------------
-- PAU : administration
-- ----------------------------
GRANT INSERT, UPDATE, DELETE ON SITE TO R_PAU_ADMIN;
GRANT INSERT, UPDATE, DELETE ON PERSON_ROLE TO R_PAU_ADMIN;

GRANT DELETE ON BUILDING TO R_PAU_ADMIN;
GRANT DELETE ON ROOM TO R_PAU_ADMIN;
GRANT DELETE ON PERSON TO R_PAU_ADMIN;
GRANT DELETE ON VLAN TO R_PAU_ADMIN;
GRANT DELETE ON NETWORK_SWITCH TO R_PAU_ADMIN;
GRANT DELETE ON DEVICE TO R_PAU_ADMIN;
GRANT DELETE ON PERIPHERAL TO R_PAU_ADMIN;
GRANT DELETE ON DEVICE_ASSIGNMENT TO R_PAU_ADMIN;

-- ============================================================
-- 5. ATTRIBUTION DES ROLES AUX SCHEMAS PRINCIPAUX
-- ============================================================
CONNECT / AS SYSDBA;
ALTER SESSION SET CONTAINER = FREEPDB1;

GRANT R_CERGY_ADMIN TO CYTECH_CERGY;
GRANT R_PAU_ADMIN TO CYTECH_PAU;

-- ============================================================
-- 6. CREATION DES UTILISATEURS DE TEST
-- ============================================================

-- ----------------------------
-- 6.1 Utilisateurs CERGY
-- ----------------------------
CREATE USER U_CERGY_READ IDENTIFIED BY cergy_read2026
DEFAULT TABLESPACE DATA_CERGY
TEMPORARY TABLESPACE TEMP;

CREATE USER U_CERGY_MANAGER IDENTIFIED BY cergy_manager2026
DEFAULT TABLESPACE DATA_CERGY
TEMPORARY TABLESPACE TEMP;

CREATE USER U_CERGY_ADMIN IDENTIFIED BY cergy_admin2026
DEFAULT TABLESPACE DATA_CERGY
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO U_CERGY_READ;
GRANT CREATE SESSION TO U_CERGY_MANAGER;
GRANT CREATE SESSION TO U_CERGY_ADMIN;

GRANT R_CERGY_READ TO U_CERGY_READ;
GRANT R_CERGY_MANAGER TO U_CERGY_MANAGER;
GRANT R_CERGY_ADMIN TO U_CERGY_ADMIN;

-- ----------------------------
-- 6.2 Utilisateurs PAU
-- ----------------------------
CREATE USER U_PAU_READ IDENTIFIED BY pau_read2026
DEFAULT TABLESPACE DATA_PAU
TEMPORARY TABLESPACE TEMP;

CREATE USER U_PAU_MANAGER IDENTIFIED BY pau_manager2026
DEFAULT TABLESPACE DATA_PAU
TEMPORARY TABLESPACE TEMP;

CREATE USER U_PAU_ADMIN IDENTIFIED BY pau_admin2026
DEFAULT TABLESPACE DATA_PAU
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO U_PAU_READ;
GRANT CREATE SESSION TO U_PAU_MANAGER;
GRANT CREATE SESSION TO U_PAU_ADMIN;

GRANT R_PAU_READ TO U_PAU_READ;
GRANT R_PAU_MANAGER TO U_PAU_MANAGER;
GRANT R_PAU_ADMIN TO U_PAU_ADMIN;

-- ============================================================
-- 7. COMMIT FINAL
-- ============================================================
COMMIT;