-- ============================================================
-- 04_replication.sql
-- Projet GLPI BDDR - Gestion des tables de reference
--
-- Choix d'architecture :
--   Les triggers bidirectionnels (ancien design) ont ete supprimes.
--   Raison : synchronisation temps-reel pour des donnees qui changent
--   2-3 fois par an = complexite injustifiee + risque de deadlock.
--
-- Nouveau principe :
--   - SITE, PERSON_ROLE, DEVICE_TYPE, PERIPHERAL_TYPE :
--       copies statiques sur les deux sites, seeded au setup.
--       Mise a jour manuelle par l'admin si besoin (evenement rare).
--   - OS_FAMILY, OS_VERSION :
--       proprietaire = Cergy uniquement.
--       Pau dispose de vues materialisees (MV_OS_FAMILY, MV_OS_VERSION)
--       refreshees a la demande (cf. section MVs dans 02_setup_pau.sql).
--
-- Pour rafraichir les MVs OS sur Pau (connecte en CYTECH_PAU) :
--   EXEC DBMS_MVIEW.REFRESH('MV_OS_FAMILY');
--   EXEC DBMS_MVIEW.REFRESH('MV_OS_VERSION');
-- ============================================================


-- ============================================================
-- VERIFICATION post-setup (optionnel)
-- ============================================================
-- Connecte en CYTECH_CERGY : verifier objets PL/SQL presents
-- SELECT object_name, object_type, status
-- FROM user_objects
-- WHERE object_type IN ('PACKAGE','PACKAGE BODY','TRIGGER','PROCEDURE','MATERIALIZED VIEW')
-- ORDER BY object_type, object_name;

-- Connecte en CYTECH_PAU : verifier les vues materialisees
-- SELECT mview_name, refresh_mode, last_refresh_date
-- FROM user_mviews;
