-- ============================================================
-- 03_setup_admin.sql
-- Roles et utilisateur d'administration.
-- A executer APRES 01_setup_cergy, 02_setup_pau ET 04_replication
-- (les MVs et procedures cross-site doivent exister).
-- Connexion : / AS SYSDBA puis container XEPDB1.
--
-- Rappel : les privileges systeme des schemas (CREATE TABLE, SEQUENCE,
-- DATABASE LINK, MATERIALIZED VIEW, PROCEDURE, TRIGGER, VIEW, SYNONYM)
-- sont accordes au bootstrap (cf. en-tete de 01_setup_cergy.sql), donc
-- avant 01/02/04.
-- ============================================================
CONNECT / AS SYSDBA
ALTER SESSION SET CONTAINER = XEPDB1;

-- ============================================================
-- 1. ROLE LECTURE SEULE (les 2 sites)
-- ============================================================
CREATE ROLE CYTECH_READER;

-- ---- CERGY : tables locales ----
GRANT SELECT ON CYTECH_CERGY.BUILDING           TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.ROOM               TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.PERSON             TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.DEVICE             TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.PERIPHERAL         TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.DEVICE_ASSIGNMENT  TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.MAINTENANCE_TICKET TO CYTECH_READER;
-- ---- CERGY : tables de reference dont Cergy est proprietaire ----
GRANT SELECT ON CYTECH_CERGY.DEVICE_TYPE        TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.OS_FAMILY          TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.OS_VERSION         TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.PERIPHERAL_TYPE    TO CYTECH_READER;
-- ---- CERGY : MVs des tables dont Pau est proprietaire ----
GRANT SELECT ON CYTECH_CERGY.MV_SITE            TO CYTECH_READER;
GRANT SELECT ON CYTECH_CERGY.MV_PERSON_ROLE     TO CYTECH_READER;

-- ---- PAU : tables locales ----
GRANT SELECT ON CYTECH_PAU.BUILDING             TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.ROOM                 TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.PERSON               TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.DEVICE               TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.PERIPHERAL           TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.DEVICE_ASSIGNMENT    TO CYTECH_READER;
-- ---- PAU : tables de reference dont Pau est proprietaire ----
GRANT SELECT ON CYTECH_PAU.SITE                 TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.PERSON_ROLE          TO CYTECH_READER;
-- ---- PAU : MVs des tables dont Cergy est proprietaire ----
GRANT SELECT ON CYTECH_PAU.MV_DEVICE_TYPE       TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.MV_PERIPHERAL_TYPE   TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.MV_OS_FAMILY         TO CYTECH_READER;
GRANT SELECT ON CYTECH_PAU.MV_OS_VERSION        TO CYTECH_READER;

-- ============================================================
-- 2. ROLE ADMIN (herite du reader + ecriture)
-- ============================================================
CREATE ROLE CYTECH_ADMIN_ROLE;
GRANT CYTECH_READER TO CYTECH_ADMIN_ROLE;

-- ---- Tables metier : INSERT / UPDATE / DELETE ----
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.PERSON             TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.DEVICE             TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.PERIPHERAL         TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.BUILDING          TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.ROOM              TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.DEVICE_ASSIGNMENT  TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_CERGY.MAINTENANCE_TICKET TO CYTECH_ADMIN_ROLE;

GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.PERSON              TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.DEVICE             TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.PERIPHERAL        TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.BUILDING          TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.ROOM             TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE, DELETE ON CYTECH_PAU.DEVICE_ASSIGNMENT  TO CYTECH_ADMIN_ROLE;

-- ---- Tables de reference : INSERT / UPDATE seulement (pas de DELETE) ----
-- Cergy proprietaire : DEVICE_TYPE, OS_FAMILY, OS_VERSION, PERIPHERAL_TYPE
GRANT INSERT, UPDATE ON CYTECH_CERGY.DEVICE_TYPE      TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_CERGY.OS_FAMILY        TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_CERGY.OS_VERSION       TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_CERGY.PERIPHERAL_TYPE  TO CYTECH_ADMIN_ROLE;
-- Pau proprietaire : SITE, PERSON_ROLE
GRANT INSERT, UPDATE ON CYTECH_PAU.SITE               TO CYTECH_ADMIN_ROLE;
GRANT INSERT, UPDATE ON CYTECH_PAU.PERSON_ROLE        TO CYTECH_ADMIN_ROLE;

-- ---- Procedures cross-site ----
GRANT EXECUTE ON CYTECH_CERGY.PROC_CREATE_TICKET   TO CYTECH_ADMIN_ROLE;
GRANT EXECUTE ON CYTECH_PAU.PROC_OPEN_TICKET_PAU   TO CYTECH_ADMIN_ROLE;

-- ============================================================
-- 3. UTILISATEUR ADMIN
-- ============================================================
CREATE USER CYTECH_ADMIN IDENTIFIED BY admin2026
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION    TO CYTECH_ADMIN;
GRANT CYTECH_ADMIN_ROLE TO CYTECH_ADMIN;

-- ============================================================
-- 4. VERIFICATION
-- ============================================================
SELECT grantee, granted_role
FROM dba_role_privs
WHERE grantee IN ('CYTECH_ADMIN', 'CYTECH_ADMIN_ROLE')
ORDER BY grantee;
